const Languages = (() => {
  const data = [
{ lang: "af", name: "Afrikaans", country: "za"},
  { lang: "sq", name: "Shqip", country: "al"},
  { lang: "am", name: "አማርኛ", country: "et"},
  { lang: "ar", name: "العربية", country: "sa"},
  { lang: "hy", name: "Հայերեն", country: "am"},
  { lang: "az", name: "Azərbaycan dili", country: "az"},
  { lang: "eu", name: "Euskara", country: "es"},
  { lang: "be", name: "Беларуская", country: "by"},
  { lang: "bn", name: "বাংলা", country: "bd"},
  { lang: "bs", name: "Bosanski", country: "ba"},
  { lang: "bg", name: "Български", country: "bg"},
  { lang: "my", name: "မြန်မာဘာသာ", country: "mm"},
  { lang: "ca", name: "Català", country: "es"},
  { lang: "zh", name: "中文", country: "cn"},
  { lang: "hr", name: "Hrvatski", country: "hr"},
  { lang: "cs", name: "Čeština", country: "cz"},
  { lang: "da", name: "Dansk", country: "dk"},
  { lang: "nl", name: "Nederlands", country: "nl"},
  { lang: "en", name: "English", country: "us"},
  { lang: "et", name: "Eesti", country: "ee"},
  { lang: "fil", name: "Filipino", country: "ph"},
  { lang: "fi", name: "Suomi", country: "fi"},
  { lang: "fr", name: "Français", country: "fr"},
  { lang: "ka", name: "ქართული", country: "ge"},
  { lang: "de", name: "Deutsch", country: "de"},
  { lang: "el", name: "Ελληνικά", country: "gr"},
  { lang: "gu", name: "ગુજરાતી", country: "in"},
  { lang: "hi", name: "हिन्दी", country: "in"},
  { lang: "hu", name: "Magyar", country: "hu"},
  { lang: "is", name: "Íslenska", country: "is"},
  { lang: "id", name: "Bahasa Indonesia", country: "id"},
  { lang: "ga", name: "Gaeilge", country: "ie"},
  { lang: "it", name: "Italiano", country: "it"},
  { lang: "ja", name: "日本語", country: "jp"},
  { lang: "jv", name: "Basa Jawa", country: "id"},
  { lang: "kn", name: "ಕನ್ನಡ", country: "in"},
  { lang: "kk", name: "Қазақ тілі", country: "kz"},
  { lang: "km", name: "ភាសាខ្មែរ", country: "kh"},
  { lang: "ko", name: "한국어", country: "kr"},
  { lang: "ku", name: "Kurdî", country: "iq"},
  { lang: "ky", name: "Кыргызча", country: "kg"},
  { lang: "lo", name: "ພາສາລາວ", country: "la"},
  { lang: "lv", name: "Latviešu", country: "lv"},
  { lang: "lt", name: "Lietuvių", country: "lt"},
  { lang: "mk", name: "Македонски", country: "mk"},
  { lang: "ms", name: "Bahasa Melayu", country: "my"},
  { lang: "ml", name: "മലയാളം", country: "in"},
  { lang: "mt", name: "Malti", country: "mt"},
  { lang: "mr", name: "मराठी", country: "in"},
  { lang: "mn", name: "Монгол", country: "mn"},
  { lang: "ne", name: "नेपाली", country: "np"},
  { lang: "no", name: "Norsk", country: "no"},
  { lang: "ps", name: "پښتو", country: "af"},
  { lang: "fa", name: "فارسی", country: "ir"},
  { lang: "pl", name: "Polski", country: "pl"},
  { lang: "pt", name: "Português", country: "pt"},
  { lang: "pa", name: "ਪੰਜਾਬੀ", country: "pk"},
  { lang: "ro", name: "Română", country: "ro"},
  { lang: "ru", name: "Русский", country: "ru"},
  { lang: "sr", name: "Српски", country: "rs"},
  { lang: "si", name: "සිංහල", country: "lk"},
  { lang: "sk", name: "Slovenčina", country: "sk"},
  { lang: "sl", name: "Slovenščina", country: "si"},
  { lang: "so", name: "Soomaali", country: "so"},
  { lang: "es", name: "Españول", country: "es"},
  { lang: "sw", name: "Kiswahili", country: "tz"},
  { lang: "sv", name: "Svenska", country: "se"},
  { lang: "tg", name: "Тоҷикӣ", country: "tj"},
  { lang: "ta", name: "தமிழ்", country: "in"},
  { lang: "te", name: "తెలుగు", country: "in"},
  { lang: "th", name: "ไทย", country: "th"},
  { lang: "tr", name: "Türkçe", country: "tr"},
  { lang: "uk", name: "Українська", country: "ua"},
  { lang: "ur", name: "اردو", country: "pk"},
  { lang: "uz", name: "O‘zbekcha", country: "uz"},
  { lang: "vi", name: "Tiếng Việt", country: "vn"},
  { lang: "cy", name: "Cymraeg", country: "gb"},
  { lang: "xh", name: "isiXhosa", country: "za"},
  { lang: "yo", name: "Yorùbá", country: "ng"},
  { lang: "zu", name: "isiZulu", country: "za"}
  ].sort((a, b) => a.name.localeCompare(b.name));

  const langToCountry = new Map(data.map(item => [item.lang, item.country]));
  const langToName = new Map(data.map(item => [item.lang, item.name]));

  return {
    data,
    langToCountry,
    langToName,
    getCountryByLang: (lang) => langToCountry.get(lang),
    getNameByLang: (lang) => langToName.get(lang)
  };
})();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = Languages;
}